"use strict";
/* content/consumption.js —— 消费/商城系统（大幅扩充版，每件可永久加 stats，引擎自动 add 应用） */
CONSUMPTION.push(
  /* ===================== 出行 ===================== */
  { id: "car_ebike", name: "电动自行车", emoji: "🛵", kind: "出行", price: 3000, assetRate: 0.1, mood: 3, social: 0,
    desc: "通勤神器，红灯一过比谁都快，就是下雨天有点惨。", stats: { body: 1 } },
  { id: "car_used", name: "二手代步车", emoji: "🚗", kind: "出行", price: 50000, assetRate: 0.3, mood: 5, social: 2,
    desc: "几万块的国产代步车，遮风挡雨，告别挤地铁。", flag: "has_car", stats: { charm: 1 } },
  { id: "car_joint", name: "合资家轿", emoji: "🚙", kind: "出行", price: 180000, assetRate: 0.32, mood: 7, social: 4,
    desc: "省心耐开的合资车，接送孩子、回老家都体面。", flag: "has_car", stats: { charm: 2 } },
  { id: "car_lux", name: "豪华轿车", emoji: "🚘", kind: "出行", price: 600000, assetRate: 0.35, mood: 10, social: 9,
    desc: "BBA 旗舰，开出去倍儿有面子。停车场里最靓的仔。", flag: "has_car", stats: { charm: 3, insight: 1 } },
  { id: "car_sport", name: "限量跑车", emoji: "🏎️", kind: "出行", price: 2800000, assetRate: 0.4, mood: 14, social: 14, repeatable: true,
    desc: "一脚油门贴背感，路人纷纷掏出手机。引擎声就是身份证。", flag: "has_car", stats: { charm: 4, insight: 1 } },

  /* ===================== 房产 ===================== */
  { id: "house_share", name: "合租一间房", emoji: "🛏️", kind: "房产", price: 60000, assetRate: 0.2, mood: 4, social: 0,
    desc: "押一付三，有了张属于自己的床。室友会不会洗碗全凭运气。", stats: { body: 1 } },
  { id: "house_small", name: "刚需小两居", emoji: "🏠", kind: "房产", price: 1500000, assetRate: 0.9, mood: 12, social: 6,
    desc: "掏空六个钱包的首付，背上三十年贷款，但总算有了自己的窝。", flag: "has_house", stats: { mind: 2 } },
  { id: "house_three", name: "改善三居室", emoji: "🏘️", kind: "房产", price: 3500000, assetRate: 0.9, mood: 13, social: 9,
    desc: "学区、地铁、电梯一应俱全，一家人终于不用再抢卫生间。", flag: "has_house", stats: { mind: 2, charm: 1 } },
  { id: "house_lux", name: "市中心大平层", emoji: "🏙️", kind: "房产", price: 8000000, assetRate: 0.9, mood: 14, social: 13,
    desc: "落地窗俯瞰全城，这就是成功的具象化。", flag: "has_house", stats: { charm: 3, insight: 2 } },
  { id: "house_villa", name: "独栋别墅", emoji: "🏡", kind: "房产", price: 25000000, assetRate: 0.9, mood: 15, social: 15,
    desc: "带泳池和私家花园，请客吃饭都得提前预约。", flag: "has_house", stats: { charm: 4, insight: 2 } },

  /* ===================== 奢侈品 ===================== */
  { id: "lux_bag", name: "名牌手袋", emoji: "👜", kind: "奢侈品", price: 30000, assetRate: 0.1, mood: 6, social: 4, repeatable: true,
    desc: "一只包顶别人半年工资。背上它，走路都带风。", stats: { charm: 1 } },
  { id: "lux_watch", name: "瑞士名表", emoji: "⌚", kind: "奢侈品", price: 150000, assetRate: 0.3, mood: 8, social: 6, repeatable: true,
    desc: "腕上的硬通货，懂的人一眼就懂。", stats: { charm: 2 } },
  { id: "lux_jewel", name: "高级珠宝", emoji: "💎", kind: "奢侈品", price: 400000, assetRate: 0.4, mood: 10, social: 8, repeatable: true,
    desc: "灯光一打，满室生辉。鸽子蛋戴上手，气场两米八。", stats: { charm: 3 } },
  { id: "lux_couture", name: "高定礼服", emoji: "👗", kind: "奢侈品", price: 800000, assetRate: 0.15, mood: 11, social: 11, repeatable: true,
    desc: "量体裁衣的孤品，红毯上独一份。", stats: { charm: 4 } },
  { id: "lux_yacht", name: "私人游艇", emoji: "🛥️", kind: "奢侈品", price: 18000000, assetRate: 0.5, mood: 15, social: 15, repeatable: true,
    desc: "海上开 party，浪花就是你的背景音乐。", flag: "has_yacht", stats: { charm: 5, insight: 2 } },

  /* ===================== 数码 ===================== */
  { id: "tech_phone", name: "最新款手机", emoji: "📱", kind: "数码", price: 10000, assetRate: 0, mood: 4, social: 2, repeatable: true,
    desc: "首发当天就入手，朋友圈第一个晒。", stats: { insight: 1 } },
  { id: "tech_laptop", name: "顶配笔记本", emoji: "💻", kind: "数码", price: 25000, assetRate: 0.1, mood: 5, social: 2, repeatable: true,
    desc: "性能拉满，工作创作两不误，开机比心动还快。", stats: { knowledge: 2 } },
  { id: "tech_camera", name: "专业相机", emoji: "📷", kind: "数码", price: 40000, assetRate: 0.15, mood: 6, social: 3, repeatable: true,
    desc: "扫街、旅拍、记录生活，按下快门那一刻治愈一切。", stats: { insight: 2, charm: 1 } },
  { id: "tech_smarthome", name: "全屋智能家居", emoji: "🏠", kind: "数码", price: 60000, assetRate: 0.2, mood: 7, social: 3,
    desc: "一句话开灯关窗扫地，从此活成科幻片主角。", stats: { mind: 1, insight: 1 } },
  { id: "tech_vr", name: "VR 头显套装", emoji: "🥽", kind: "数码", price: 8000, assetRate: 0, mood: 5, social: 1, repeatable: true,
    desc: "戴上就进元宇宙，挥拳打怪、云端旅行，摘下来扶墙走。", stats: { insight: 1 } },

  /* ===================== 体验 ===================== */
  { id: "exp_travel", name: "出国深度游", emoji: "✈️", kind: "体验", price: 40000, assetRate: 0, mood: 14, social: 3, health: 4, repeatable: true,
    desc: "请几天假，去看看不一样的世界。九宫格照片已备好。", stats: { insight: 2 } },
  { id: "exp_concert", name: "天王演唱会", emoji: "🎤", kind: "体验", price: 5000, assetRate: 0, mood: 12, social: 2, repeatable: true,
    desc: "内场摇滚区蹦到嗓子哑，散场后耳朵嗡嗡响了三天。", stats: { mind: 1 } },
  { id: "exp_michelin", name: "米其林三星", emoji: "🍽️", kind: "体验", price: 8000, assetRate: 0, mood: 10, social: 4, repeatable: true,
    desc: "一口一个心跳价，摆盘精致到不敢下叉。", stats: { insight: 1, charm: 1 } },
  { id: "exp_diving", name: "潜水考证", emoji: "🤿", kind: "体验", price: 15000, assetRate: 0, mood: 11, social: 2, health: 5, repeatable: true,
    desc: "考下 OW 证，下潜到海底与鱼群同游，世界瞬间安静。", stats: { body: 2, insight: 2 } },
  { id: "exp_ski", name: "雪场滑雪季", emoji: "🎿", kind: "体验", price: 20000, assetRate: 0, mood: 11, social: 3, health: 4, repeatable: true,
    desc: "从高级道一冲到底，风在耳边呼啸，摔得越惨笑得越开。", stats: { body: 2 } },
  { id: "exp_marathon", name: "全程马拉松", emoji: "🏃", kind: "体验", price: 3000, assetRate: 0, mood: 12, social: 2, health: 6, repeatable: true,
    desc: "42 公里跑下来腿不是自己的，但冲线那刻热泪盈眶。", stats: { body: 3, strategy: 1 } },

  /* ===================== 健康养生 ===================== */
  { id: "well_pt", name: "健身私教课", emoji: "💪", kind: "健康养生", price: 20000, assetRate: 0, mood: 4, social: 1, health: 10, repeatable: true,
    desc: "私教一对一，把身体练回来，撸铁到怀疑人生。", stats: { body: 4 } },
  { id: "well_nutri", name: "营养师定制", emoji: "🥗", kind: "健康养生", price: 12000, assetRate: 0, mood: 3, social: 1, health: 6, repeatable: true,
    desc: "三餐按克称重，戒糖戒油，身体一天天轻盈起来。", stats: { body: 2, mind: 1 } },
  { id: "well_checkup", name: "高端体检套餐", emoji: "🩺", kind: "健康养生", price: 8000, assetRate: 0, mood: 3, social: 1, health: 8, repeatable: true,
    desc: "从头到脚扫一遍，早发现早安心，报告全绿那天最幸福。", stats: { body: 2 } },
  { id: "well_tcm", name: "中医调理", emoji: "🍵", kind: "健康养生", price: 15000, assetRate: 0, mood: 4, social: 1, health: 7, repeatable: true,
    desc: "针灸推拿加膏方，把熬夜亏的元气一点点补回来。", stats: { body: 2, insight: 1 } },
  { id: "well_medbeauty", name: "医美抗衰", emoji: "💉", kind: "健康养生", price: 50000, assetRate: 0, mood: 6, social: 3, health: 2, repeatable: true,
    desc: "光子嫩肤加水光针，照镜子年轻五岁，自信值拉满。", stats: { charm: 3 } },

  /* ===================== 学习提升 ===================== */
  { id: "edu_bookclub", name: "高端读书会", emoji: "📚", kind: "学习提升", price: 6000, assetRate: 0, mood: 5, social: 2, repeatable: true,
    desc: "一群人围读经典，思辨交锋，散场还能换张名片。", network: 2, stats: { knowledge: 2 } },
  { id: "edu_course", name: "付费精品课", emoji: "🎓", kind: "学习提升", price: 9000, assetRate: 0, mood: 4, social: 1, repeatable: true,
    desc: "行业大牛亲授，知识付费不焦虑，学完真能涨本事。", stats: { knowledge: 3 } },
  { id: "edu_mba", name: "读个 MBA", emoji: "🏛️", kind: "学习提升", price: 400000, assetRate: 0, mood: 8, social: 6,
    desc: "商学院两年，学的是案例，攒的是人脉，毕业即升咖。", network: 4, stats: { strategy: 4, knowledge: 2 } },
  { id: "edu_piano", name: "钢琴一对一", emoji: "🎹", kind: "学习提升", price: 30000, assetRate: 0, mood: 7, social: 2, repeatable: true,
    desc: "从拜厄练到肖邦，指尖流淌的不只是音符，还有气质。", stats: { charm: 2, mind: 2 } },
  { id: "edu_speech", name: "演讲口才培训", emoji: "🎙️", kind: "学习提升", price: 18000, assetRate: 0, mood: 5, social: 2, repeatable: true,
    desc: "台上一站不再腿软，金句脱口而出，开会发言全场侧目。", stats: { charm: 2, strategy: 2 } },

  /* ===================== 陪伴 ===================== */
  { id: "comp_cat", name: "养一只猫", emoji: "🐱", kind: "陪伴", price: 6000, assetRate: 0, mood: 10, social: 1, repeatable: false,
    desc: "高冷主子赏脸踩你两脚奶，撸毛的瞬间一身疲惫烟消云散。", flag: "has_pet", stats: { mind: 1 } },
  { id: "comp_dog", name: "养一只狗", emoji: "🐕", kind: "陪伴", price: 8000, assetRate: 0, mood: 11, social: 1, repeatable: false,
    desc: "一只毛茸茸的小家伙，从此家里多了个等你回家的。", flag: "has_pet", stats: { body: 1, mind: 1 } },
  { id: "comp_fish", name: "造一缸鱼", emoji: "🐠", kind: "陪伴", price: 5000, assetRate: 0.1, mood: 8, social: 1, repeatable: false,
    desc: "水草摇曳、灯光氤氲，看鱼发呆是当代最廉价的禅修。", flag: "has_pet", stats: { mind: 2 } },

  /* ===================== 尽孝 ===================== */
  { id: "filial_supp", name: "给爸妈买保健品", emoji: "🧧", kind: "尽孝", price: 8000, assetRate: 0, mood: 8, social: 0, repeatable: true,
    desc: "正规渠道的钙片鱼油，叮嘱他们别再信养生群里的偏方。", custom: (s) => { socialBoostRole(s, "爸妈", 8); add(s, "reputation", 1); } },
  { id: "filial_trip", name: "带爸妈去旅游", emoji: "🧳", kind: "尽孝", price: 40000, assetRate: 0, mood: 12, social: 2, repeatable: true,
    desc: "陪他们看一次海，拍下他们像孩子一样的笑脸。", custom: (s) => { socialBoostRole(s, "爸妈", 12); add(s, "reputation", 2); }, stats: { insight: 1 } },
  { id: "filial_house", name: "给爸妈买套房", emoji: "🏡", kind: "尽孝", price: 1000000, assetRate: 0.5, mood: 14, social: 3,
    desc: "让操劳一辈子的父母，住进有电梯的新房。", custom: (s) => { socialBoostRole(s, "爸妈", 18); add(s, "reputation", 4); } },

  /* ===================== 公益 ===================== */
  { id: "charity_donate", name: "捐一笔善款", emoji: "❤️", kind: "公益", price: 200000, assetRate: 0, mood: 8, social: 0, reputation: 15, repeatable: true,
    desc: "捐给山区小学。图的不是名，是心安。", custom: (s) => { socialShift(s, 2); socialBoostRole(s, "老同学", 10); } },
  { id: "charity_teach", name: "去支教一学期", emoji: "✏️", kind: "公益", price: 30000, assetRate: 0, mood: 12, social: 0, reputation: 10, repeatable: true,
    desc: "在大山里教孩子认字，离开那天全村送你到村口。", custom: (s) => { socialShift(s, 2); }, stats: { insight: 2, mind: 1 } },
  { id: "charity_volunteer", name: "长期做志愿者", emoji: "🤝", kind: "公益", price: 5000, assetRate: 0, mood: 9, social: 0, reputation: 6, repeatable: true,
    desc: "敬老院、救援队、马拉松补给站，红马甲一穿就是一整年。", custom: (s) => { socialShift(s, 1); }, network: 2, stats: { body: 1 } },

  /* ===================== 心理 ===================== */
  { id: "mind_therapy", name: "心理咨询", emoji: "🛋️", kind: "心理", price: 20000, assetRate: 0, mood: 9, social: 0, repeatable: true,
    desc: "在咨询室里把堵了多年的话说出来，肩上的石头轻了。", stats: { mind: 3 } },
  { id: "mind_mindful", name: "正念冥想课", emoji: "🧘", kind: "心理", price: 8000, assetRate: 0, mood: 8, social: 0, repeatable: true,
    desc: "每天十分钟观呼吸，把跑飞的念头一只只请回来。", stats: { mind: 2 } },
  { id: "mind_detox", name: "数字戒断营", emoji: "📵", kind: "心理", price: 12000, assetRate: 0, mood: 7, social: 0, health: 3, repeatable: true,
    desc: "上交手机进山七天，第一天抓心挠肝，第七天神清气爽。", stats: { mind: 2, body: 1 } },

  /* ===================== 形象 ===================== */
  { id: "img_gym", name: "塑形健身年卡", emoji: "🏋️", kind: "形象", price: 6000, assetRate: 0, mood: 5, social: 2, health: 6, repeatable: true,
    desc: "练出马甲线/胸肌，换季衣服小一码，回头率肉眼可见。", stats: { body: 3, charm: 1 } },
  { id: "img_stylist", name: "私人穿搭顾问", emoji: "🧥", kind: "形象", price: 15000, assetRate: 0, mood: 6, social: 3, repeatable: true,
    desc: "把衣柜全盘重组，原来你不是不好看，是没穿对。", stats: { charm: 3 } },
  { id: "img_dental", name: "牙齿正畸美白", emoji: "🦷", kind: "形象", price: 40000, assetRate: 0, mood: 6, social: 2, repeatable: false,
    desc: "戴两年牙套换一口白牙，从此敢放声大笑。", stats: { charm: 2 } },
  { id: "img_hair", name: "植发养固", emoji: "💇", kind: "形象", price: 50000, assetRate: 0, mood: 8, social: 2, repeatable: false,
    desc: "发际线重回二十岁，照片再也不用 P 头发了。", stats: { charm: 3 } },

  /* ===================== 分期负债 ===================== */
  { id: "debt_phone_plan", name: "手机十二期免息", emoji: "📱", kind: "分期负债", price: 1200, assetRate: 0, mood: 5, social: 3, repeatable: true,
    desc: "首付很轻，账单很长。新手机到手那刻，未来十二个月已经排队等你。", stats: { insight: 1 },
    custom: (s) => { add(s, "overdraft", 3); add(s, "stress", 2); flag(s, "installment_user"); } },
  { id: "debt_car_downpay", name: "车贷首付上车", emoji: "🚙", kind: "分期负债", price: 45000, assetRate: 1.2, mood: 8, social: 6,
    desc: "先把车开回家，月供以后再说。朋友圈很体面，银行卡很清醒。", flag: "has_car", stats: { charm: 2 },
    custom: (s) => { add(s, "overdraft", 12); add(s, "stress", 6); socialBoostRole(s, "爸妈", 3); flag(s, "car_loan"); } },
  { id: "debt_house_downpay", name: "房贷首付上岸", emoji: "🏠", kind: "分期负债", price: 350000, assetRate: 2.8, mood: 12, social: 8,
    desc: "钥匙拿到手，三十年还款计划也拿到手。安稳和压力从此同居。", flag: "has_house", stats: { mind: 2 },
    custom: (s) => { add(s, "overdraft", 25); add(s, "stress", 10); socialBoostRole(s, "爸妈", 8); flag(s, "mortgage"); } },
  { id: "debt_lux_credit", name: "信用卡刷名表", emoji: "⌚", kind: "分期负债", price: 30000, assetRate: 0.4, mood: 7, social: 9, repeatable: true,
    desc: "表是真的，账单也是真的。懂表的人夸你，清醒的人替你捏汗。", stats: { charm: 2 },
    custom: (s) => { add(s, "overdraft", 10); add(s, "stress", 5); socialShift(s, 2); flag(s, "credit_showoff"); } },

  /* ===================== 租赁共享 ===================== */
  { id: "rent_commute_car", name: "长期租车通勤", emoji: "🚘", kind: "租赁共享", price: 9000, assetRate: 0, mood: 5, social: 3, repeatable: true,
    desc: "不用养车也能开车，雨天和加班夜都舒服一点。只是车钥匙永远不真正属于你。", stats: { charm: 1 },
    custom: (s) => { add(s, "stress", -2); flag(s, "rent_car_user"); } },
  { id: "rent_dress", name: "礼服租赁", emoji: "👗", kind: "租赁共享", price: 3000, assetRate: 0, mood: 6, social: 5, repeatable: true,
    desc: "重要场合穿得像样，不必把衣柜变成资金黑洞。拍照够用，体面也够用。", stats: { charm: 1 },
    custom: (s) => { socialShift(s, 1); } },
  { id: "rent_office_desk", name: "共享办公工位", emoji: "🏢", kind: "租赁共享", price: 5000, assetRate: 0, mood: 4, social: 2, repeatable: true,
    desc: "一张桌子、一杯咖啡、一群同样焦虑的人。适合自由职业，也适合创业前夜。", network: 2, stats: { strategy: 1 },
    custom: (s) => { if (has(s, "startup")) { s.startup.progress += 2; add(s, "stress", -1); } flag(s, "coworking"); } },
  { id: "rent_camera", name: "器材租赁周末拍", emoji: "📷", kind: "租赁共享", price: 2500, assetRate: 0, mood: 6, social: 3, repeatable: true,
    desc: "不用买全套镜头，也能拍出像回事的作品。朋友圈负责点赞，押金负责提醒。", stats: { insight: 1 } },

  /* ===================== 二手精明 ===================== */
  { id: "used_laptop", name: "二手高配电脑", emoji: "💻", kind: "二手精明", price: 9000, assetRate: 0.25, mood: 4, social: 1,
    desc: "上一任机主替你承担了折旧，你拿它剪视频、写代码、做方案，性价比很香。", stats: { knowledge: 2 } },
  { id: "used_parent_car", name: "亲戚旧车接手", emoji: "🚗", kind: "二手精明", price: 25000, assetRate: 0.45, mood: 4, social: 1,
    desc: "车况一般但知根知底，过户那天亲戚还叮嘱你别猛踩油门。", flag: "has_car", stats: { charm: 1 },
    custom: (s) => { socialBoostRole(s, "亲戚", 5); add(s, "stress", -1); } },
  { id: "used_baby_goods", name: "二手育儿大件", emoji: "🧸", kind: "二手精明", price: 6000, assetRate: 0.15, mood: 5, social: 0, repeatable: true,
    desc: "婴儿车、安全座椅、绘本架，别人家闲置到你家刚需，省下的钱能买不少奶粉。", stats: { mind: 1 },
    custom: (s) => { if (has(s, "has_kid")) socialBoostRole(s, "孩子", 6); add(s, "stress", -2); } },
  { id: "used_lux_bag", name: "二手奢侈包", emoji: "👜", kind: "二手精明", price: 12000, assetRate: 0.2, mood: 5, social: 4, repeatable: true,
    desc: "成色不错，价格腰斩。会买的人看门道，爱酸的人看标签。", stats: { charm: 1 },
    custom: (s) => { socialShift(s, 1); } },

  /* ===================== 订阅服务 ===================== */
  { id: "sub_streaming", name: "影音会员全家桶", emoji: "📺", kind: "订阅服务", price: 1200, assetRate: 0, mood: 5, social: 0, repeatable: true,
    desc: "想看的剧不用到处找资源，周末窝在沙发里也算认真生活。", stats: { mind: 1 } },
  { id: "sub_ai_tools", name: "AI 工具订阅", emoji: "🤖", kind: "订阅服务", price: 3600, assetRate: 0, mood: 4, social: 2, repeatable: true,
    desc: "写方案、做图、整理资料都快一截。会用工具的人，像偷偷多长了一只手。", stats: { knowledge: 2, insight: 1 },
    custom: (s) => { if (has(s, "startup")) s.startup.progress += 3; flag(s, "ai_tools"); } },
  { id: "sub_cloud_office", name: "云办公套件", emoji: "☁️", kind: "订阅服务", price: 2400, assetRate: 0, mood: 3, social: 1, repeatable: true,
    desc: "文件不丢、协作不乱、会议纪要能找回来。小钱买秩序。", stats: { strategy: 1 },
    custom: (s) => { if (has(s, "startup")) s.startup.progress += 2; } },
  { id: "sub_elder_care", name: "父母远程看护订阅", emoji: "🩺", kind: "订阅服务", price: 6000, assetRate: 0, mood: 6, social: 0, repeatable: true,
    desc: "体征提醒、用药记录、上门巡护，不能天天陪在身边，也尽量把心放近一点。", stats: { mind: 1 },
    custom: (s) => { socialBoostRole(s, "爸妈", 10); add(s, "stress", -4); add(s, "reputation", 1); } },

  /* ===================== 子女投入 ===================== */
  { id: "kid_interest_class", name: "孩子兴趣班", emoji: "🎨", kind: "子女投入", price: 12000, assetRate: 0, mood: 6, social: 2, repeatable: true,
    desc: "画画、篮球、机器人，总得让孩子试试看喜欢什么。家长群也顺手多认识几个人。", network: 1, stats: { mind: 1 },
    custom: (s) => { if (has(s, "has_kid")) socialBoostRole(s, "孩子", 10); add(s, "stress", 2); } },
  { id: "kid_tutor", name: "一对一补课", emoji: "📘", kind: "子女投入", price: 30000, assetRate: 0, mood: 4, social: 3, repeatable: true,
    desc: "老师进门，账单跟着进门。分数也许会上去，亲子关系要看火候。", stats: { strategy: 1 },
    custom: (s) => { if (has(s, "has_kid")) socialBoostRole(s, "孩子", 6); add(s, "stress", 5); } },
  { id: "kid_international_school", name: "国际学校学费", emoji: "🏫", kind: "子女投入", price: 180000, assetRate: 0, mood: 8, social: 7, repeatable: true,
    desc: "双语环境、海外课程、家长会上的车钥匙声。教育选择，也是一种阶层表达。", network: 3, stats: { insight: 1 },
    custom: (s) => { if (has(s, "has_kid")) socialBoostRole(s, "孩子", 12); socialShift(s, 2); add(s, "stress", 6); } },
  { id: "kid_study_abroad_fund", name: "子女留学基金", emoji: "✈️", kind: "子女投入", price: 300000, assetRate: 0.1, mood: 9, social: 6, repeatable: true,
    desc: "给未来先存一张远方的船票。钱躺进去，你心里也踏实一点。", stats: { insight: 2 },
    custom: (s) => { if (has(s, "has_kid")) socialBoostRole(s, "孩子", 15); add(s, "reputation", 2); flag(s, "kid_abroad_fund"); } },

  /* ===================== 父母照护 ===================== */
  { id: "parent_checkup_plus", name: "父母深度体检", emoji: "🧾", kind: "父母照护", price: 18000, assetRate: 0, mood: 8, social: 0, health: 1, repeatable: true,
    desc: "把小毛病尽早查出来，比在电话里说一百遍注意身体更实在。", stats: { mind: 1 },
    custom: (s) => { socialBoostRole(s, "爸妈", 12); add(s, "stress", -3); } },
  { id: "parent_caregiver", name: "请护工照料父母", emoji: "🤲", kind: "父母照护", price: 36000, assetRate: 0, mood: 7, social: 0, repeatable: true,
    desc: "专业的人陪诊、做饭、盯药，你终于不用在工作和病房之间撕成两半。", stats: { mind: 1 },
    custom: (s) => { socialBoostRole(s, "爸妈", 16); add(s, "stress", -8); add(s, "reputation", 1); } },
  { id: "parent_old_home", name: "高端养老社区押金", emoji: "🏡", kind: "父母照护", price: 500000, assetRate: 0.35, mood: 10, social: 4,
    desc: "环境、医护、活动都安排上了。父母嘴上嫌贵，背地里把房间照片发给老朋友。", stats: { mind: 2 },
    custom: (s) => { socialBoostRole(s, "爸妈", 20); socialShift(s, 1); add(s, "reputation", 3); } },

  /* ===================== 创业采购 ===================== */
  { id: "biz_brand_package", name: "创业品牌包装", emoji: "🎯", kind: "创业采购", price: 20000, assetRate: 0, mood: 5, social: 3, repeatable: true,
    desc: "Logo、官网、路演模板一口气做齐。产品还小，气势先不能输。", stats: { charm: 1, strategy: 1 },
    custom: (s) => { if (has(s, "startup")) { s.startup.progress += 4; add(s, "reputation", 2); } flag(s, "brand_ready"); } },
  { id: "biz_legal_accounting", name: "法务财税顾问", emoji: "⚖️", kind: "创业采购", price: 30000, assetRate: 0, mood: 3, social: 1, repeatable: true,
    desc: "合同、股权、发票、社保，提前补课总比踩坑后补票便宜。", stats: { strategy: 2 },
    custom: (s) => { if (has(s, "startup")) { s.startup.progress += 3; add(s, "stress", -4); } flag(s, "legal_ready"); } },
  { id: "biz_server_credit", name: "云服务器额度", emoji: "🖥️", kind: "创业采购", price: 15000, assetRate: 0, mood: 4, social: 1, repeatable: true,
    desc: "访问量真来了，服务器先别塌。技术债可以慢慢还，宕机不能当场演。", stats: { knowledge: 1 },
    custom: (s) => { if (has(s, "startup")) s.startup.progress += 5; } },
  { id: "biz_trade_show", name: "行业展会展位", emoji: "🏟️", kind: "创业采购", price: 80000, assetRate: 0, mood: 7, social: 7, repeatable: true,
    desc: "灯箱一亮、易拉宝一摆，你的公司终于像个公司。客户和同行都会路过看一眼。", network: 4, stats: { charm: 1 },
    custom: (s) => { if (has(s, "startup")) { s.startup.progress += 8; add(s, "reputation", 4); } socialShift(s, 2); } },
  { id: "biz_founder_club", name: "创业者俱乐部会费", emoji: "🥂", kind: "创业采购", price: 100000, assetRate: 0, mood: 8, social: 10, repeatable: true,
    desc: "饭局、闭门会、投资人茶叙。有人真交流，有人真炫耀，你最好分得清。", network: 5, stats: { strategy: 1 },
    custom: (s) => { if (has(s, "startup")) { s.startup.progress += 4; add(s, "reputation", 3); } socialShift(s, 3); flag(s, "founder_club"); } }
);
